files:
  include: 'styles/**/*.s+(a|c)ss'
  ignore:
    - 'styles/modules/vendor/**/*.scss'
rules:
  indentation:
    - 2
  hex-notation:
    - 1
    - style: lowercase
  no-color-keywords: 0
  no-color-literals: 0
  class-name-format:
    - 1
    - convention: hyphenatedbem
  no-trailing-whitespace: 0
  nesting-depth:
    - 1
    - max-depth: 3
  pseudo-element: 0
  final-newline: 0
  empty-line-between-blocks: 0
  no-important: 0
  force-pseudo-nesting: 0
  extends-before-declarations: 0
  placeholder-in-extend: 0
  property-sort-order: 0
